"""Domain-oriented storage interface and backend factory."""

from contextlib import contextmanager
import os
from typing import Iterator, Protocol

from domain.intelligence.clustering import ClusteredEvent
from domain.registry.source import CanonicalSourcePolicy
from evidence import EvidenceRecord
from shadow_learning import ObservationRecord, ShadowDecision, OutcomeLabel, AdaptiveEvidence, JobCheckpoint


class StorageRepository(Protocol):
    def list_source_policies(self) -> list[CanonicalSourcePolicy]: ...
    def get_source_policy(self, source_id: str) -> CanonicalSourcePolicy | None: ...
    def save_source_policy(self, policy: CanonicalSourcePolicy) -> CanonicalSourcePolicy: ...
    def save_evidence(self, record: EvidenceRecord) -> None: ...
    def get_evidence(self, evidence_id: str) -> EvidenceRecord | None: ...
    def save_clustered_event(self, event: ClusteredEvent) -> None: ...
    def list_clustered_events(self) -> list[ClusteredEvent]: ...
    def append_audit_event(self, action: str, entity_type: str | None = None,
                           entity_id: str | None = None, after: dict | None = None) -> None: ...
    def save_observation(self, record: ObservationRecord) -> None: ...
    def save_shadow_decision(self, decision: ShadowDecision) -> None: ...
    def save_outcome(self, outcome: OutcomeLabel) -> None: ...
    def save_adaptive_evidence(self, evidence: AdaptiveEvidence) -> None: ...
    def contribute_adaptive_evidence(self, evidence: AdaptiveEvidence, outcome_id: str) -> bool: ...
    def learning_status(self) -> dict: ...
    def get_observation(self, observation_id: str) -> dict | None: ...
    def get_shadow_decision(self, decision_id: str) -> dict | None: ...
    def get_outcome(self, outcome_id: str) -> dict | None: ...
    def get_job(self, job_key: str) -> dict | None: ...
    def save_job(self, job: JobCheckpoint) -> None: ...
    def ensure_job(self, job: JobCheckpoint) -> None: ...
    def due_jobs(self, now: str, limit: int = 1) -> list[JobCheckpoint]: ...
    def claim_job(self, job_key: str, worker_id: str, now: str) -> JobCheckpoint | None: ...
    def finish_job(self, running: JobCheckpoint, done: JobCheckpoint) -> bool: ...
    def recover_jobs(self, now: str, *, limit: int = 1, lease_seconds: int = 300, keys=None) -> list[JobCheckpoint]: ...
    def save_worker_status(self, status: dict) -> None: ...
    def counts(self) -> dict[str, int]: ...
    def save_reliability_outcome(self, record: dict) -> None: ...
    def list_reliability_outcomes(self, source_id: str, scope_key: str, horizon: str) -> list[dict]: ...
    @contextmanager
    def transaction(self) -> Iterator[None]: ...


def get_storage_repository(*, database_url: str | None = None, sqlite_path: str = "market_intelligence.db") -> StorageRepository:
    url = database_url if database_url is not None else os.environ.get("DATABASE_URL")
    if url and url.lower().startswith(("postgresql://", "postgres://")):
        from .postgres_repository import PostgresRepository
        return PostgresRepository(url)
    from .sqlite_repository import SQLiteRepository
    return SQLiteRepository(sqlite_path)
