"""Broker-neutral capability and adapter protocol."""
from typing import Protocol

class BrokerAdapter(Protocol):
 @property
 def capabilities(self)->dict[str,bool]:...
 def authenticate(self):...
 def search_markets(self,query):...
 def get_instrument(self,instrument_id):...
 def get_historical_prices(self,*args,**kwargs):...
 def subscribe_prices(self,*args,**kwargs):...
 def get_account(self):...
 def get_positions(self):...
 def preview_order(self,intent):...
 def place_order(self,intent,**kwargs):...
 def amend_order(self,*args,**kwargs):...
 def cancel_order(self,order_id):...
 def close_position(self,position_id,**kwargs):...
 def get_order_status(self,order_id):...
 def reconcile(self):...

class UnsupportedBrokerCapability(RuntimeError):pass

__all__=['BrokerAdapter','UnsupportedBrokerCapability']
