"""Independently specified toy calendar and arithmetic expectations."""
from datetime import datetime, timedelta, timezone
from decimal import Decimal as D
from domain.backtest.data import Bar, Manifest, Session


def fixture(prices=None, product='EQUITY', currency='ZAR'):
    # Friday, Monday, Tuesday, Thursday (Wednesday is a declared toy holiday).
    dates = (2, 5, 6, 8, 9, 12, 13, 14, 15, 16)
    sessions = tuple(Session(str(i), datetime(2026, 10, day, 7, tzinfo=timezone.utc),
                             datetime(2026, 10, day, 15, tzinfo=timezone.utc)) for i, day in enumerate(dates))
    prices = prices or [(100, 101, 99, 100), (100, 103, 99, 102),
                        (102, 105, 101, 104), (104, 106, 103, 105), (105, 107, 104, 106)]
    bars = tuple(Bar(str(i), sessions[i].close_at, *(D(str(x)) for x in row), D(1000)) for i, row in enumerate(prices))
    return Manifest('TOY', product, currency, 'HAND_CALCULATED', sessions[-1].close_at,
                    'RAW', 'TRADED_SHARES' if product == 'EQUITY' else 'NONE',
                    'TOY_HOLIDAY_CALENDAR', True, 'SYNTHETIC', 'FIXED_TOY', 'NONE_VERIFIED', '1', sessions, bars)


# These numbers are pencil arithmetic, never generated by the simulator:
# decision Friday close -> Monday close 102; stop 90; target 126.
# Three sessions AFTER entry: Tue, Thu, Fri -> 106; ten shares -> gross 40.
# Cash 2000 - 1020 - entry fee 2 = 978; sale 1060 - exit fee 2 -> 2036.
ORACLE = {'entry': 102, 'exit': 106, 'quantity': 10, 'gross_pnl': 40,
          'fees': 4, 'final_cash': 2036, 'held': 3}
